export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_USER_ACTIVATED = 'SET_USER_ACTIVATED';
export const SET_USER_DEACTIVATED = 'SET_USER_DEACTIVATED';
